// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

let _client: SupabaseClient<Database> | null = null;

export function getSupabaseClient(): SupabaseClient<Database> | null {
  if (_client) return _client;
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) return null;

  _client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  });

  return _client;
}

export function getSupabaseConfigStatus():
  | { ok: true }
  | { ok: false; missing: Array<"VITE_SUPABASE_URL" | "VITE_SUPABASE_PUBLISHABLE_KEY"> } {
  const missing: Array<"VITE_SUPABASE_URL" | "VITE_SUPABASE_PUBLISHABLE_KEY"> = [];
  if (!SUPABASE_URL) missing.push("VITE_SUPABASE_URL");
  if (!SUPABASE_PUBLISHABLE_KEY) missing.push("VITE_SUPABASE_PUBLISHABLE_KEY");
  return missing.length === 0 ? { ok: true } : { ok: false, missing };
}